#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook "apt"
cookbook "build-essential"
cookbook "postgresql", github: "phlipper/chef-postgresql"
cookbook "rvm", github: "fnichol/chef-rvm"
